# Purpose: send a monthly report to Crossref of error messages

name: crossref-error-report

on:
  # TODO: turn cron on after review
  # schedule: 
  #   # 'Runs at 06:40, on day 6 of the month'
  #   - cron: '40 6 6 * *'
  workflow_dispatch:

jobs:
  crossref-error-report:
    uses: ./.github/workflows/email_automate.yml
    with:
      automation: 'Crossref'
    secrets: inherit
