# Purpose: generate a CSV report of submission errors 
# from Thoth submissions to Crossref, to periodically send back to Crossref.

name: crossref-error-report

on:
  schedule: 
    # Runs every Monday at 06:40 UTC
    - cron: '40 6 * * 1'
  workflow_dispatch:

jobs:
  crossref-error-report:
    uses: ./.github/workflows/email_automate.yml
    with:
      automation: 'Crossref'
    secrets: inherit
