# Logic shared between multiple workflows for email automation
name: email-automate

on:
  workflow_call:
    inputs:
      automation:
        required: true
        type: string
  # workflow_dispatch:
  #   inputs:
  #     automation:
  #       required: true
  #       type: choice
  #       description: 'Email automation to run'
  #       options:
  #         - Crossref

jobs:
  email-automate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Make all platform credentials available to later steps (with names lowercased)
        uses: oNaiPs/secrets-to-env-action@v1.5
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Run email automator
        # env:
        #   IMAP_SERVER: ${{ secrets.IMAP_SERVER }}
        #   IMAP_USERNAME: ${{ secrets.IMAP_USERNAME }}
        #   IMAP_PASSWORD: ${{ secrets.IMAP_PASSWORD }}
        #   THOTH_SMTP: ${{ secrets.THOTH_SMTP }}
        #   CROSSREF_EMAIL: ${{ secrets.CROSSREF_EMAIL }}
        run: python email_automator.py --automation "${{ inputs.automation }}"

      # - name: Upload output to artifact
      #   uses: actions/upload-artifact@v4
      #   if: contains(fromJSON('["InternetArchive", "CUL", "Figshare", "Zenodo"]'), inputs.platform)
      #   with:
      #     name: ${{ inputs.work-id }}
      #     path: ${{ inputs.work-id }}
      #     retention-days: 7
      #     if-no-files-found: ignore
      #     overwrite: false
