name: crossref-error-report

on:
  workflow_dispatch:

jobs:
  fetch_crossref_emails:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run Crossref email fetch script
        env:
          IMAP_SERVER: ${{ secrets.IMAP_SERVER }}
          IMAP_USERNAME: ${{ secrets.IMAP_USERNAME }}
          IMAP_PASSWORD: ${{ secrets.IMAP_PASSWORD }}
        run: python src/generate_error_report.py
